# Generated by Django 5.2.10 on 2026-01-16 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_quizscore"),
        ("quiz", "0003_create_admin_user"),
    ]

    operations = []
